자동차 게임 구현
hyojhand/java-racingcar-playground pull request #2
Opened 2023-02-07 11:26 UTC by hyojhand

### 기능 요구사항
- 각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.
- 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- 자동차 이름은 쉼표(,)를 기준으로 구분한다.
- 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
- 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한명 이상일 수 있다.

### 프로그래밍 요구사항
- 함수(또는 메소드)가 한 가지 일만 하도록 최대한 작게 만들어라.
- 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.
- 모든 원시 값과 문자열을 포장한다.
- 일급 컬렉션을 쓴다.

2023-02-13 05:33 UTC, hyojhand commented
### 테스트하기 어려운 부분 분리 - 랜덤값에 대한 테스트

Car 객체에서 자동차가 전진하는 move 메서드를 테스트하기 쉽게 만들기 위해, 
GenerateNumber(랜덤값 생성)과 분리하여, 파라미터로 숫자를 받고 해당 숫자가 4이상이면 전진하도록 구현했습니다.

이후에 CarGame의 moveOrStop에서 랜덤 값에 의해 전진하도록 구현했는데, 
랜덤값으로 인해 테스트하기 어려움을 느꼈습니다.

이를 랜덤값과 다시 분리하여 컨트롤러에서 랜덤값을 생성한 리스트를 받아오고
Cars의 Car들이 각자 다른 랜덤값으로 전진하도록 리팩토링 했습니다.

2023-02-20 12:57 UTC, hyunssooo requested changes
안녕하세요 많이 늦었습니다. 
몇 가지 코멘트 남겼는데요. 함께 고민해 보면 좋을 것 같아요.

2023-02-20 12:57 UTC, hyunssooo commented on src/main/java/racingcar/controller/GameController.java
> +    private static final GenerateNumber generateNumber = new GenerateNumber();
도메인 모델이 컨트롤러 필드에 존재한다면 동시성 이슈는 없을까요?

2023-02-20 12:57 UTC, hyunssooo commented on src/main/java/racingcar/controller/GameController.java
> +        Cars cars = new Cars(carNames);
일급컬렉션 💯

2023-02-20 12:57 UTC, hyunssooo commented on src/main/java/racingcar/controller/GameController.java
> +    }
Cars 내부를 꺼내기 보다 Cars에게 메세지를 보내볼 수 없을까요?

2023-02-20 12:57 UTC, hyunssooo commented on src/main/java/racingcar/domain/Car.java
> +    }
랜덤 의존성 제거 💯 
Car 를 불변 객체로 만들어 보는 것은 어떨까요?
어떤 장단점이 있을까요?

2023-02-20 12:57 UTC, hyunssooo commented on src/main/java/racingcar/domain/CarGame.java
> +    }
우승자는 여러명이 될 수 있지 않나요? 
해당 클래스의 많은 로직은 Cars에게 위임할 수 있지 않을까요?

2023-02-20 12:57 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarTest.java
> +    }
`@ParameterizedTest` 👍 
car 객체 내부를 꺼내 검증하기 보다 객체끼리 비교해 검증하는 방법은 어떨까요?

2023-02-21 04:45 UTC, hyojhand commented on src/main/java/racingcar/controller/GameController.java
> +    private static final GenerateNumber generateNumber = new GenerateNumber();
인스턴스 변수로 변경했습니다.

2023-02-21 04:46 UTC, hyojhand commented on src/main/java/racingcar/controller/GameController.java
> +    }
getter 메서드를 사용하지 않고, 객체에 메시지를 보내도록 수정했습니다!
객체를 꺼내서 사용하지 않고, 객체에 메시지를 보내는 습관을 가져야겠네요.

2023-02-21 04:49 UTC, hyojhand commented on src/main/java/racingcar/domain/Car.java
> +    }
불변 객체로 만든다면 외부에 의해 인스턴스의 데이터가 변하지 않는 안전한 코드가 될 수 있습니다.
하지만, 인스턴스가 자주 만들어져 성능 저하가 문제될 것 같지만, 성능상 크게 문제가 되지 않는다면 
불변 객체로 사용하는게 안전한 코드가 될 것 같습니다.

2023-02-21 04:49 UTC, hyojhand commented on src/main/java/racingcar/domain/CarGame.java
> +    }
가장 최대 위치값과 우승자를 확인하는 로직을 Cars로 위임하였고,
Car 객체에서 파라미터로 받는 최대 위치값과 같다면 우승자임을 반환하도록 분리했습니다.

2023-02-21 04:50 UTC, hyojhand commented on src/test/java/racingcar/domain/CarTest.java
> +    }
테스트를 위해 생성자를 열어놓는게 좋은가에 대해 고민했습니다.
기존에는 이름만 파라미터로 받아서 이동횟수를 0으로 초기화하여, 
임의의 이동횟수가 들어간 객체가 생성되지 않게 생성자를 하나만 사용했습니다.
실수로라도 잘못된 객체가 만들어질 수 있는 방법을 차단하기 위한 의도로 로직에 불필요한 생성자를 만들지 않았습니다.

하지만, 이동 메서드를 불필요하게 반복해서 테스트를 위한 상태로 만들어야 했고, 테스트에 어려움이 있었습니다.
테스트를 위해 생성자를 사용하는 것도 하나의 방법이라고 하여 생성자를 추가해서 
테스트 상황에 맞는 객체를 만들고, 재정의된 equals 메서드를 활용해 객체끼리 비교가 가능하도록 했습니다.

2023-02-21 04:55 UTC, hyojhand commented
추가 리팩토링
1. 불변객체로 리팩토링하면서 Car 객체의 원시값을 포장해 일급 객체로 만들었습니다.
그로인해 이름의 길이에 대한 예외처리도 Name 클래스에 책임을 부여하도록 했습니다.
2. 출력되는 문자(",")와 관련된 메서드는 view단으로 분리했습니다. (mappingName메서드)
3. 객체를 꺼내서 사용하지 않고, 객체에 메시지를 보내도록 리팩토링했습니다.
그로인해 view 단에서 출력하는 과정에서 필요한 원시값으로 인해 getter가 필요한 상황 외에는 
getter 메서드를 사용하지 않도록 리팩토링할 수 있었습니다.

2023-02-26 16:09 UTC, hyunssooo approved these changes
바빠서 많이 늦었네요. 죄송합니다.🥲
몇 가지 코멘트 남겼어요. 다음 스텝 진행하면서 확인 부탁드려요.

2023-02-26 16:09 UTC, hyunssooo commented on src/main/java/racingcar/domain/Position.java
> +
`Comparable` 인터페이스를 찾아보고 구현해 보는 것은 어떨까요?
이번 미션에서 활용할 수 있을까요?

2023-02-26 16:09 UTC, hyunssooo commented on src/main/java/racingcar/domain/Cars.java
> +    }
객체에세 메세지를 보낸 점 💯 
`List<Car>` 보다 Winners 객체를 리턴하면 좀 더 자연스럽지 않을까요?
모델링 관점에서 
- `Cars` 에서 `findWinners` 하면 `List<Car>` 를 받는다.
- `Cars` 에서 `findWinners` 하면 `Winners` 를 받는다.

어떤 경우가 모델링이 자연스럽다고 볼 수 있을까요?

2023-02-26 16:09 UTC, hyunssooo commented on src/main/java/racingcar/view/OutputView.java
> +    }
```java
winners.stream()
            .map(it -> it.getName().getName())
            .collect(Collectors.joining(", "));
```

스트림을 활용해 보면 좋을 것 같아요.

2023-02-26 16:09 UTC, hyunssooo commented on src/main/java/racingcar/domain/CarGame.java
> +    }
cars에서 getter를 사용하는 부분은 제거 할 수 없을까요?? 
`GenerateNumber`를 Cars의 메서드 파라미터로 넘겨주면 되지 않을까요?

2023-02-26 16:09 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarGameTest.java
> +
매 테스트 마다 객체를 생성하는 편이 테스트하기 편하지 않나요?? 
static으로 선언한 이유가 따로 있을까요?

2023-02-26 16:09 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarGameTest.java
> +
```java
  @BeforeEach
  void setUp() {
    carGame = new CarGame();
  }
```

2023-02-26 16:09 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarsTest.java
> +
findWinners 는 테스트가 힘들까요?

2023-02-26 16:09 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarTest.java
> +    @DisplayName("Car 객체 테스트")
조금 더 명확한 설명이 필요합니다. 
객체 테스트는 어떤 테스트인가요?

2023-02-26 16:09 UTC, hyunssooo commented on src/test/java/racingcar/domain/CarTest.java
> +    @ValueSource(ints = {4, 5, 6, 7, 8, 9})
`@ParameterizedTest` 👍

2023-02-26 16:09 UTC, merged